### ISSUE TITLE
input属性，提示不存在类型

### ISSUE THREAD

**Issue by wou101771** [CaoMeiYouRen/vite-plugin-swagger-typescript-api#2]
![image](https://user-images.githubusercontent.com/52279380/213901840-c34dec09-1d67-4925-8bbf-dcc9007141d9.png)

**Comment by l1m2e** [comment]
url 属性也提示不存在类型 
![image](https://user-images.githubusercontent.com/62976143/234734928-308d9a35-4de9-45ea-9222-5ddd267c8de3.png)
